name: Release binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Get version
      shell: bash
      run: |
        version=$(echo ${GITHUB_REF_NAME} | sed -e 's/^v//')
        echo "BUILD_VER=$version" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: |
        go get .

    - name: Set build name with tag
      shell: bash
      run: echo "BUILD_NAME=nomadstate-${GITHUB_REF_NAME}-${{ matrix.os == 'windows-latest' && 'windows-amd64.exe' || 'linux-amd64' }} " >> $GITHUB_ENV

    - name: Build
      run: go build -o ${{ env.BUILD_NAME }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          nomadstate*
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
